name: macosko2015-env
channels:
- bioconda
- r
- defaults
- conda-forge
dependencies:
- jupyter
- notebook
- pandas
- xarray
- seaborn
- matplotlib
- pip:
  - args
  - click
  - clint
  - ipython-genutils
  - jupyter-client
  - jupyter-console
  - jupyter-core
  - pkginfo
  - polo
  - prompt-toolkit
  - requests-toolbelt
  - tqdm
  - twine

